In [8]:
from d2l import torch

X = torch.arange(15).reshape(3, -1)

X

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [2]:
Y = torch.arange(3, 6)
Y

tensor([3, 4, 5])

In [3]:
X + Y

tensor([3, 5, 7])

In [4]:
X[:] = X + Y
Z = X <= Y

In [5]:
Z

tensor([ True, False, False])

In [6]:
X[2] = 40

In [7]:
X

tensor([ 3,  5, 40])

////////////////////////////////////-------------------------------/////////////////////////////////////

In [32]:
A = torch.ones(3,3)
A[0, 0] = 2
A[1, 0] = 0
A

tensor([[2., 1., 1.],
        [0., 1., 1.],
        [1., 1., 1.]])

In [38]:
A.sum(axis=1, keepdims=True)

tensor([[4.],
        [2.],
        [3.]])

In [37]:
A / A.sum(axis=1, keepdims=True)

tensor([[0.5000, 0.2500, 0.2500],
        [0.0000, 0.5000, 0.5000],
        [0.3333, 0.3333, 0.3333]])